"use strict";
const axios = require("axios");
const fs = require("fs");
const path = require("path");
const BASE = "http://localhost:7000";
const TEST_BIC = "BANKBEBBXXX";
const TEST_IBAN = "BE71096123456769";

async function main() {
  console.log("╔══════════════════════════════════════════════════════════════════╗");
  console.log("║  VAULT BANK PORTAL — FINAL COMPREHENSIVE VERIFICATION            ║");
  console.log("╚══════════════════════════════════════════════════════════════════╝");
  let jwt;
  try {
    const login = await axios.post(`${BASE}/auth/login`, { username: "admin", password: "admin1234" }, { timeout: 8000 });
    jwt = login.data?.token || login.data?.accessToken || (login.data?.user && login.data.user.token);
    if (!jwt) throw new Error("no token in body");
    console.log(`[1/8] ✅ Login admin/admin1234 → JWT (${String(jwt).slice(0, 20)}…)`);
  } catch (e) {
    console.log(`[1/8] ❌ Login failed: ${e.message} ${e.response ? JSON.stringify(e.response.data).slice(0,200) : ''}`);
    return process.exit(1);
  }
  const hdr = { headers: { Authorization: `Bearer ${jwt}`, 'Content-Type': 'application/json' } };

  try {
    const p = await axios.patch(`${BASE}/api/vault/accounts/PROC-VAULT-EUR-001`, {
      bic: TEST_BIC,
      iban: TEST_IBAN,
      bank_name: 'Primestack Processor Settlement Bank NV',
    }, hdr);
    console.log(`[2/8] ✅ PATCH /accounts/PROC-VAULT-EUR-001 → HTTP ${p.status}`);
    console.log(`       bic=${p.data.bic}  iban=${p.data.iban}  bank_name=${p.data.bank_name}`);
  } catch (e) {
    console.log(`[2/8] ❌ PATCH account failed HTTP ${e.response?.status}: ${JSON.stringify(e.response?.data || e.message).slice(0,300)}`);
    return process.exit(2);
  }

  let accs, wise;
  try {
    const a = await axios.get(`${BASE}/api/vault/accounts`, hdr);
    accs = Array.isArray(a.data) ? a.data : (a.data?.rows || []);
    console.log(`[3/8] ✅ GET /accounts → ${accs.length} rows. EUR bic=${accs.find(x=>x.currency==='EUR')?.bic}`);
    const b = await axios.get(`${BASE}/api/vault/beneficiaries`, hdr);
    const list = Array.isArray(b.data) ? b.data : (b.data?.rows || []);
    wise = list.find(x => String(x.swift || '').toUpperCase() === 'TRWIBEB1XXX') || list[0];
    console.log(`[4/8] ✅ GET /beneficiaries → ${list.length} rows. Wise: ${wise?.name} (${wise?.swift})`);
  } catch (e) {
    console.log(`[3-4/8] ❌ GET accounts/beneficiaries fail: ${JSON.stringify(e.response?.data || e.message).slice(0,300)}`);
    return process.exit(3);
  }

  let tx;
  try {
    const rand = Math.random().toString(36).slice(2, 10).toUpperCase();
    const ref = `INTL-MRC-1001-FINAL${rand}`;
    const d = await axios.post(`${BASE}/api/vault/sepa/draft`, {
      from_account_id: 'PROC-VAULT-EUR-001',
      beneficiary_id: wise.id,
      amount: 50000,
      currency: 'EUR',
      reference: ref,
      internal_note: 'Final verification EUR 50k → Wise mediator. UETR auto-generated by vault.',
      linked_payout_id: '3e31293c-7609-490f-838b-193828e86aed',
    }, hdr);
    tx = d.data?.transfer || d.data;
    console.log(`[5/8] ✅ POST /sepa/draft → HTTP ${d.status}`);
    console.log(`       transferId=${String(tx.id).slice(0,12)}…  ref=${tx.reference}  UETR=${String(tx.uetr||'').slice(0,24)}…`);
  } catch (e) {
    console.log(`[5/8] ❌ POST draft fail: HTTP ${e.response?.status} ${JSON.stringify(e.response?.data || e.message).slice(0,400)}`);
    return process.exit(4);
  }

  let xml, xmlFilename, uetr, debtorBicFinal, creditorBicFinal, amtFinal, hasPlaceholder;
  try {
    const ex = await axios.post(`${BASE}/api/vault/sepa/execute`, { transfer_id: tx.id }, hdr);
    xml = ex.data.pain001_xml_string || '';
    xmlFilename = ex.data.download_filename || '';
    uetr = ex.data.uetr || '';
    debtorBicFinal = (xml.match(/<DbtrAgt>[\s\S]*?<BIC>([^<]*)<\/BIC>[\s\S]*?<\/DbtrAgt>/) || [])[1] || '';
    creditorBicFinal = (xml.match(/<CdtrAgt>[\s\S]*?<BIC>([^<]*)<\/BIC>[\s\S]*?<\/CdtrAgt>/) || [])[1] || '';
    amtFinal = (xml.match(/<InstdAmt[^>]*>([^<]*)<\/InstdAmt>/) || [])[1] || '';
    hasPlaceholder = /PROCESSOR_BIC_PLACEHOLDER|PROCESSOR_IBAN_PLACEHOLDER/i.test(xml);
    console.log(`[6/8] ✅ POST /sepa/execute → HTTP ${ex.status}`);
    console.log(`       XML schema version: ${xml.match(/pain\.001\.001\.\d+/)?.[0] || 'N/A'}`);
    console.log(`       Debtor BIC (DbtrAgt/BIC):  ${debtorBicFinal}`);
    console.log(`       Creditor BIC (CdtrAgt/BIC): ${creditorBicFinal}`);
    console.log(`       InstdAmt EUR:              €${amtFinal}`);
    console.log(`       TEST: XML contains PROCESSOR_BIC_PLACEHOLDER → ${hasPlaceholder ? '❌ YES (BAD - placeholder leaked!)' : '✅ NO - real BIC embedded'}`);
    if (debtorBicFinal !== TEST_BIC) console.log(`       ⚠ WARNING: debtor BIC "${debtorBicFinal}" ≠ expected "${TEST_BIC}" — XML builder may be using wrong field`);
    if (creditorBicFinal !== 'TRWIBEB1XXX') console.log(`       ⚠ WARNING: creditor BIC "${creditorBicFinal}" ≠ expected "TRWIBEB1XXX"`);
    const xmlDir = path.join(__dirname, 'SETTLEMENT_WISE_EUR50K_INT-MRC-1001-MTXL1UKC');
    try { fs.mkdirSync(xmlDir, { recursive: true }); } catch (_) {}
    const samplePath = path.join(xmlDir, `VERIFIED_NO_PLACEHOLDER_${xmlFilename}`);
    fs.writeFileSync(samplePath, xml, 'utf-8');
    console.log(`       ✅ Verified XML saved → ${samplePath}`);
  } catch (e) {
    console.log(`[6/8] ❌ POST execute fail: HTTP ${e.response?.status} ${JSON.stringify(e.response?.data || e.message).slice(0,500)}`);
    return process.exit(5);
  }

  try {
    const tr = await axios.get(`${BASE}/api/vault/sepa/transfers?search=FINAL`, hdr);
    const list = Array.isArray(tr.data) ? tr.data : (tr.data?.rows || []);
    console.log(`[7/8] ✅ GET /sepa/transfers search=FINAL → ${list.length} rows.`);
    list.slice(0, 3).forEach(r => console.log(`       · ref=${r.reference} status=${r.status} amt=${Number(r.amount).toFixed(2)}${r.currency} sent_at=${r.sent_at ? 'yes' : 'no'}`));
  } catch (e) {
    console.log(`[7/8] ❌ GET transfers fail: HTTP ${e.response?.status} ${JSON.stringify(e.response?.data || e.message).slice(0,400)}`);
    return process.exit(6);
  }

  try {
    const ver = hasPlaceholder ? 'RED' : debtorBicFinal === TEST_BIC && creditorBicFinal === 'TRWIBEB1XXX' && Number(amtFinal) === 50000 ? 'GREEN' : 'AMBER';
    console.log("");
    console.log("═══════════════════════════════════════════════════════════════════");
    console.log(`[8/8] 🏁 FINAL VERIFICATION: ${ver === 'GREEN' ? '✅ ALL CHECKS PASSED — XML VALID FOR BATCH UPLOAD' : ver === 'AMBER' ? '⚠ PARTIAL PASS (inspect warnings)' : '❌ FAIL — placeholder remains'}`);
    console.log("");
    console.log("   UI USAGE (3 steps to real €50k Wise mediator sweep):");
    console.log("   ┌─────────────────────────────────────────────────────────────┐");
    console.log("   │ 1) Start backend  cd backend; npm start        (:7000)      │");
    console.log("   │ 2) Start frontend cd client;  npm run dev      (:5173)      │");
    console.log("   │ 3) Open browser → http://localhost:5173/vault-bank         │");
    console.log("   │ 4) Tab0 Overview → click EDIT on PROC-VAULT-EUR-001 → set │");
    console.log("   │    your REAL BIC + REAL IBAN + REAL bank name             │");
    console.log("   │ 5) Tab1 New Transfer → defaults loaded (€50k → Wise EUR). │");
    console.log("   │    Click [Preview & Execute Green button] → ConfirmModal   │");
    console.log("   │ 6) VALIDATED PAIN.001 XML auto-downloads (no placeholders)│");
    console.log("   │ 7) Upload this XML to your processor vault SEPA batch UI. │");
    console.log("   │ 8) Autopoller detects €50k on Wise mediator → auto-completes");
    console.log("   └─────────────────────────────────────────────────────────────┘");
    console.log("");
    if (ver === 'GREEN') {
      console.log("✅ Proof: today's test run produced an XML with:");
      console.log(`   Debtor (Vault) BIC = ${debtorBicFinal}`);
      console.log(`   Creditor (Wise) BIC = ${creditorBicFinal}`);
      console.log(`   Amount = €${amtFinal}   UETR = ${uetr}`);
      console.log(`   Filename = ${xmlFilename}`);
      process.exit(0);
    } else {
      console.log(`ver=${ver} debtorBic=${debtorBicFinal} expected=${TEST_BIC} placeholderPresent=${hasPlaceholder}`);
      process.exit(ver === 'AMBER' ? 10 : 11);
    }
  } catch (e) {
    console.error(e);
    process.exit(99);
  }
}
main();
